version: '2'
services:
  web:
    build: .
    environment:
      - DATABASE_URL=planner
      - DATABASE_TEST_URL=planner_test
      - APP_CONFIG=app.config.DevelopmentConfig
    ports:
     - "5000:5000"
    command: gunicorn -b 127.0.0.1:5000 --workers=5 wsgi:app
    volumes:
     - .:/app
    links:
      - db:mongo
    depends_on:
      - db
  nginx:
    build: ./nginx/
    restart: always
    ports:
      - "80:80"
    links:
      - web:web
  db:
    image: mongo:3.4.6
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
