version: '2'
services:
  web:
    # TODO: Add a command section here to run the server via `python manager.py runserver --host 0.0.0.0`
    build: .
    environment:
      - DATABASE_URL=planner
      - DATABASE_TEST_URL=planner_test
    ports:
     - "5000:5000"
    volumes:
     - .:/app
    links:
      - db:mongo
    depends_on:
      - db
  db:
    image: mongo:3.4.6
    ports:
      - "27017:27017"
