version: '2'
services:
  web:
    build: .
    environment:
      - DATABASE_URL=plans-db
      - DATABASE_TEST_URL=plans-test-db
    ports:
     - "5000:5000"
    volumes:
     - .:/app
    links:
      - db:mongo
    depends_on:
      - db
  db:
    image: mongo:3.4.6
    ports:
      - "27017:27017"
